name: Publish Development Package

on:
  push:
    branches:
      - main

jobs:
  publish-dev:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22
          registry-url: https://npm.pkg.github.com/

      - name: Set up Git User
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Install Dependencies
        run: npm ci

      - name: Build Package
        run: npm run build

      - name: Publish Development Package
        run: |
          npm version prerelease --preid=dev
          npm publish --tag dev
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}